declare module 'app_alegra_commons/utils'
declare module 'app_alegra_commons/app'
declare module 'app_alegra_commons/session'
declare module 'app_alegra_commons/config'
declare module 'app_alegra_commons/translate'
declare module 'app_alegra_commons/appFloatingButton'
